---
font: DejaVuSans.ttf
lower: 32
upper: 3583
size: 12
default: ascii

#JIS X 0208 (Japanese)
---
font: ipagp.ttf
lower: 8213 
upper: 9839
size: 16

#JIS X 0208 (Japanese)
---
font: ipagp.ttf
lower: 12288
upper: 12543
size: 16

# Plartform specifig (Japanese)
---
font: ipagp.ttf
lower: 12800
upper: 12879
size: 16

# Plartform specifig (Japanese)
---
font: ipagp.ttf
lower: 12800
upper: 12879
size: 16

# Plartform specifig (Japanese)
---
font: ipagp.ttf
lower: 12800
upper: 12879
size: 16


# Plartform specifig (Japanese)
---
font: ipagp.ttf
lower: 12928
upper: 13311
size: 16

#JIS X 0208 (Japanese)
---
font: ipagp.ttf
lower: 19968
upper: 40864
size: 16

---
font: odokai.ttf
lower: 13312
upper: 19967

# JIS X 0208 (Japanese)
---
font: ipagp.ttf
lower: 65280
upper: 65519
size: 16

